//! The templates this program is built with.
//!
//! Every file in the repository's `templates/` directory, compiled in. They
//! are data the program is useless without - a summary of a file the user did
//! not download a template for is no summary at all - so they travel inside
//! the binary rather than beside it, and a single-file install has the whole
//! set. Templates fetched at runtime are read from disk on top of these, the
//! way a downloaded theme is.
//!
//! Generated from the directory listing; a new file under `templates/` needs a
//! line here to be built in.

/// The text of every shipped template, in path order.
pub const BUILTIN: &[&str] = &[
    include_str!("../../templates/archive/7z.toml"),
    include_str!("../../templates/archive/bzip2.toml"),
    include_str!("../../templates/archive/cab.toml"),
    include_str!("../../templates/archive/cpio-newc.toml"),
    include_str!("../../templates/archive/cpio-odc.toml"),
    include_str!("../../templates/archive/gzip.toml"),
    include_str!("../../templates/archive/lz4.toml"),
    include_str!("../../templates/archive/rar.toml"),
    include_str!("../../templates/archive/rpm.toml"),
    include_str!("../../templates/archive/tar-ustar.toml"),
    include_str!("../../templates/archive/xz.toml"),
    include_str!("../../templates/archive/zip-eocd.toml"),
    include_str!("../../templates/archive/zip-local.toml"),
    include_str!("../../templates/archive/zstd.toml"),
    include_str!("../../templates/crypto/der.toml"),
    include_str!("../../templates/crypto/luks1.toml"),
    include_str!("../../templates/crypto/luks2.toml"),
    include_str!("../../templates/crypto/pgp-packet.toml"),
    include_str!("../../templates/data/avro.toml"),
    include_str!("../../templates/data/hdf5.toml"),
    include_str!("../../templates/data/parquet.toml"),
    include_str!("../../templates/data/pcap-be.toml"),
    include_str!("../../templates/data/pcap-le.toml"),
    include_str!("../../templates/data/pcapng.toml"),
    include_str!("../../templates/disk/qcow2.toml"),
    include_str!("../../templates/disk/vdi.toml"),
    include_str!("../../templates/disk/vhd.toml"),
    include_str!("../../templates/disk/vhdx.toml"),
    include_str!("../../templates/disk/vmdk.toml"),
    include_str!("../../templates/doc/olecf.toml"),
    include_str!("../../templates/doc/pdf.toml"),
    include_str!("../../templates/doc/sqlite.toml"),
    include_str!("../../templates/exe/ar.toml"),
    include_str!("../../templates/exe/class.toml"),
    include_str!("../../templates/exe/dex.toml"),
    include_str!("../../templates/exe/dos-header.toml"),
    include_str!("../../templates/exe/elf32.toml"),
    include_str!("../../templates/exe/elf64-phdr.toml"),
    include_str!("../../templates/exe/elf64.toml"),
    include_str!("../../templates/exe/lua.toml"),
    include_str!("../../templates/exe/macho-fat.toml"),
    include_str!("../../templates/exe/macho64.toml"),
    include_str!("../../templates/exe/pe-header.toml"),
    include_str!("../../templates/exe/pyc.toml"),
    include_str!("../../templates/exe/wasm.toml"),
    include_str!("../../templates/firmware/android-boot.toml"),
    include_str!("../../templates/firmware/dtb.toml"),
    include_str!("../../templates/firmware/efi-capsule.toml"),
    include_str!("../../templates/firmware/uefi-fv.toml"),
    include_str!("../../templates/firmware/uimage.toml"),
    include_str!("../../templates/font/otf.toml"),
    include_str!("../../templates/font/ttf.toml"),
    include_str!("../../templates/font/woff.toml"),
    include_str!("../../templates/font/woff2.toml"),
    include_str!("../../templates/forensics/bplist.toml"),
    include_str!("../../templates/forensics/evtx.toml"),
    include_str!("../../templates/forensics/lnk.toml"),
    include_str!("../../templates/forensics/macho-superblob.toml"),
    include_str!("../../templates/forensics/mft-record.toml"),
    include_str!("../../templates/forensics/minidump.toml"),
    include_str!("../../templates/forensics/pdb.toml"),
    include_str!("../../templates/forensics/prefetch.toml"),
    include_str!("../../templates/forensics/regf.toml"),
    include_str!("../../templates/fs/apfs-nx.toml"),
    include_str!("../../templates/fs/btrfs.toml"),
    include_str!("../../templates/fs/exfat-vbr.toml"),
    include_str!("../../templates/fs/ext-superblock.toml"),
    include_str!("../../templates/fs/f2fs.toml"),
    include_str!("../../templates/fs/fat16-bpb.toml"),
    include_str!("../../templates/fs/fat32-bpb.toml"),
    include_str!("../../templates/fs/hfsplus.toml"),
    include_str!("../../templates/fs/iso9660-pvd.toml"),
    include_str!("../../templates/fs/jffs2.toml"),
    include_str!("../../templates/fs/ntfs-boot.toml"),
    include_str!("../../templates/fs/squashfs.toml"),
    include_str!("../../templates/fs/udf-anchor.toml"),
    include_str!("../../templates/fs/xfs.toml"),
    include_str!("../../templates/image/bmp.toml"),
    include_str!("../../templates/image/ftyp.toml"),
    include_str!("../../templates/image/gif.toml"),
    include_str!("../../templates/image/ico.toml"),
    include_str!("../../templates/image/jpeg.toml"),
    include_str!("../../templates/image/png.toml"),
    include_str!("../../templates/image/psd.toml"),
    include_str!("../../templates/image/qoi.toml"),
    include_str!("../../templates/image/tga.toml"),
    include_str!("../../templates/image/tiff-be.toml"),
    include_str!("../../templates/image/tiff-le.toml"),
    include_str!("../../templates/image/webp.toml"),
    include_str!("../../templates/media/aiff.toml"),
    include_str!("../../templates/media/asf.toml"),
    include_str!("../../templates/media/au.toml"),
    include_str!("../../templates/media/avi.toml"),
    include_str!("../../templates/media/flac.toml"),
    include_str!("../../templates/media/id3v2.toml"),
    include_str!("../../templates/media/matroska.toml"),
    include_str!("../../templates/media/midi.toml"),
    include_str!("../../templates/media/mpeg-ts.toml"),
    include_str!("../../templates/media/ogg.toml"),
    include_str!("../../templates/media/opus.toml"),
    include_str!("../../templates/media/wav.toml"),
    include_str!("../../templates/part/el-torito.toml"),
    include_str!("../../templates/part/gpt-entry.toml"),
    include_str!("../../templates/part/gpt-header.toml"),
    include_str!("../../templates/part/mbr.toml"),
    include_str!("../../templates/rom/gameboy.toml"),
    include_str!("../../templates/rom/ines.toml"),
    include_str!("../../templates/rom/n64.toml"),
    include_str!("../../templates/rom/snes-lorom.toml"),
];
